services:
  - type: web
    name: rocket-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build:api
    startCommand: npm run start:api
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase: rocket-db
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AI_PROVIDER
        value: openrouter
      - key: AI_MODEL
        value: openrouter/anthropic/claude-3.5-sonnet
      - key: AAVE_RPC_URL
        sync: false
      - key: AAVE_NETWORK
        value: polygon
      - key: AAVE_POOL_ADDRESS_PROVIDER
        sync: false
      - key: OBP_BASE_URL
        value: https://apisandbox.openbankproject.com
      - key: OBP_CONSUMER_KEY
        sync: false
      - key: OBP_CONSUMER_SECRET
        sync: false
      - key: OBP_USERNAME
        sync: false
      - key: OBP_PASSWORD
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
  - type: web
    name: rocket-web
    env: node
    plan: starter
    buildCommand: npm install && npm run build:web
    startCommand: npm run start:web
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_API_BASE
        value: https://rocket-api.onrender.com

databases:
  - name: rocket-db
    plan: starter